### ISSUE TITLE
Really... create the feature

### ISSUE THREAD

**Issue by fenago** [fenago/public-repo#2]
feature request

**Comment by fenago** [comment]
@fenago #1 

```[tasklist]
### Tasks
- [ ] https://github.com/fenago/public-repo/issues/2
- [ ] Draft issue title
```

**Comment by fenago** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/fenago/public-repo/issues/1
- [ ] Draft issue title
```
